apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: ems-namespace
spec:
  selector:
    app: department-service
  ports:
    - port: 8082
      targetPort: 8082
    - port: 9090
      name: grpc
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
  namespace: ems-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
        - name: department-service
          image: department-service:latest
          ports:
            - containerPort: 8082
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: DEPARTMENT_DB_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: POSTGRES_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: EUREKA_URL
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: RABBITMQ_HOST
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: REDIS_HOST
