apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - infrastructure.yaml
  - eureka.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - employee-service.yaml
  - department-service.yaml
  - notification-service.yaml
  - payroll-service.yaml
