apiVersion: v1
kind: Secret
metadata:
  name: ems-secrets
  namespace: ems-namespace
type: Opaque
stringData:
  POSTGRES_PASSWORD: "admin123"
  JWT_SECRET: "VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9ySFM1MTI="
  RABBITMQ_PASS: "secret"
  MAIL_PASSWORD: "your_mail_password"
