apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: ems-namespace
spec:
  selector:
    app: stock-service
  ports:
    - port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  namespace: ems-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
        - name: stock-service
          image: stock-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: EUREKA_URL
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: RABBITMQ_HOST
            - name: SPRING_CASSANDRA_CONTACT_POINTS
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: CASSANDRA_CONTACT_POINTS
            - name: SPRING_CASSANDRA_KEYSPACE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: CASSANDRA_KEYSPACE
            - name: SPRING_CASSANDRA_LOCAL_DATACENTER
              valueFrom:
                configMapKeyRef:
                  name: ems-config
                  key: CASSANDRA_LOCAL_DATACENTER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: JWT_SECRET
