spring.application.name=stock-service
server.port=8085
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Security Secret
jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9ySFM1MTI=

# Resilience4j Configuration
resilience4j.circuitbreaker.instances.externalStockApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.externalStockApi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.externalStockApi.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.externalStockApi.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.externalStockApi.maxAttempts=3
resilience4j.retry.instances.externalStockApi.waitDuration=1000

# External API Config (Placeholder)
external.stock.api.url=https://api.example.com/stocks
